// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebSiteArchitect.AdminAPI.Model;

namespace WebSiteArchitect.AdminAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171204163455_updatemenu")]
    partial class updatemenu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSiteArchitect.AdminAPI.Model.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ControlsJson")
                        .HasColumnName("Controls");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("ModDate");

                    b.Property<string>("Name");

                    b.Property<int>("SiteId");

                    b.Property<string>("XamlPageString")
                        .HasColumnName("XamlPage");

                    b.HasKey("MenuId");

                    b.HasIndex("SiteId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("WebSiteArchitect.AdminAPI.Model.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ControlsJson")
                        .HasColumnName("Controls");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("ModDate");

                    b.Property<string>("Name");

                    b.Property<int>("SiteId");

                    b.Property<string>("XamlPageString")
                        .HasColumnName("XamlPage");

                    b.HasKey("PageId");

                    b.HasIndex("SiteId");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("WebSiteArchitect.AdminAPI.Model.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("ModDate");

                    b.Property<string>("Name");

                    b.Property<int>("StartPage");

                    b.HasKey("SiteId");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("WebSiteArchitect.AdminAPI.Model.Menu", b =>
                {
                    b.HasOne("WebSiteArchitect.AdminAPI.Model.Site", "Site")
                        .WithMany("Menus")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebSiteArchitect.AdminAPI.Model.Page", b =>
                {
                    b.HasOne("WebSiteArchitect.AdminAPI.Model.Site", "Site")
                        .WithMany("Pages")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
